block-beta
columns 3
  IN("User-Defined XML"):3
  blockArrowId1<["&nbsp;&nbsp;&nbsp;"]>(down):3
  block:Builder["Builder"]:3
  columns 3
    space:1
    Reader["Reader"]:1
    space:1
    space:3
    A["Parser"]:1
    space:1
    B["Transformer"]:1
    space:1
    C["Generator"]:1
    space:1
    Reader --> A
    A --> B
    B --> C
  end
  blockArrowId2<["&nbsp;&nbsp;&nbsp;"]>(down):3
  OUT("ASTERTIX Data Types"):3
  